/**
 * gender :
 *  0 : féminim
 *  1 : masculin
 */
export default {
    order: [
        ['sujets.nomCommuns', 'verbes', 'sujets.nom'],
        [
            'sujets.nom',
            'verbes',
            'adverbes.quantite',
            'adjectifs.possessif',
            'sujets.nomCommuns',
        ],
        ['sujets.nomCommuns', 'verbes', 'adverbes.maniere', 'sujets.nom'],
        [
            'sujets.nomCommuns',
            'verbes',
            'adjectifs.possessif',
            'sujets.nomCommuns',
            'adverbes.quantite',
        ],
        [
            'sujets.nomCommuns',
            'verbes',
            'adjectifs.possessif',
            'sujets.nomCommuns',
        ],
        [
            'sujets.nom',
            'verbes',
            'adjectifs.possessif',
            'sujets.nomCommuns',
            'prepositions.maniere',
            'sujets.nom',
        ],
        [
            'sujets.pronoms',
            'verbes',
            'adjectifs.possessif',
            'sujets.nomCommuns',
            'prepositions.maniere',
            'sujets.nom',
        ],
        [
            'sujets.nomCommuns',
            'verbes',
            'sujets.nomCorps',
            'prepositions.appartenance',
            'sujets.nom',
        ],
        [
            'sujets.nomCommuns',
            'verbes',
            'sujets.nomCorps',
            'prepositions.appartenance',
            'adjectifs.possessif',
            'sujets.nomCommuns',
        ],
        [
            'sujets.nomCommuns',
            'verbes',
            'sujets.nomCorps',
            'prepositions.appartenance',
            'adjectifs.possessif',
            'sujets.nomCommuns',
            'locutions.adjectivales',
        ],
        [
            'sujets.nomCommuns',
            'verbes',
            'sujets.nomCorps',
            'prepositions.appartenance',
            'adjectifs.possessif',
            'sujets.nomCommuns',
            'locutions.conjonctives',
            'sujets.nomCommuns',
            'verbes',
        ],
        // conjonctives
    ],
    adjectifs: {
        /**
         * gender 1 si le nom qui suit commence par une voyelle
         */
        possessif: [
            { value: 'son', gender: 1 },
            { value: 'mon', gender: 1 },
            { value: 'ton', gender: 1 },
            { value: 'ma', gender: 0 },
            { value: 'sa', gender: 0 },
            { value: 'ta', gender: 0 },
            { value: 'notre', gender: 2 },
            { value: 'votre', gender: 2 },
            { value: 'leur', gender: 2 },
        ],
    },
    pronomsObjet: [
        {
            value: 'le',
            withVoyelle: "l'",
            gender: 1,
        },
        {
            value: 'la',
            withVoyelle: "l'",
            gender: 0,
        },
        {
            value: 'les',
            gender: 2,
        },
    ],
    sujets: {
        nomCommuns: [
            { value: 'jardinier', gender: 1 },
            { value: 'voisin', gender: 1 },
            { value: 'facteur', gender: 1 },
            { value: 'boulangère', gender: 0 },
            { value: 'cousin', gender: 1 },
            { value: 'cousine', gender: 0 },
            { value: 'père', gender: 1 },
            { value: 'mère', gender: 0 },
            { value: 'voisine', gender: 0 },
            { value: 'curé', gender: 1 },
            { value: 'président', gender: 1 },
            { value: 'maçon', gender: 1 },
            { value: 'arbre', gender: 1 },
            { value: 'astraunote', gender: 1 },
            { value: 'menuisier', gender: 1 },
            { value: 'factrice', gender: 0 },
            { value: 'équipe de rugby', gender: 0 },
            { value: 'grand mère', gender: 0 },
            { value: 'collègue', gender: 1 },
            { value: 'camarade', gender: 1 },
            { value: 'camarade', gender: 0 },
            { value: 'chat', gender: 1 },
        ],
        nom: [
            { value: 'Stefan', gender: 1 },
            { value: 'Matthieu', gender: 1 },
            { value: 'Martine', gender: 0 },
            { value: 'Josiane', gender: 0 },
            { value: 'François', gender: 1 },
            { value: 'Micheline', gender: 0 },
            { value: 'René Coty', gender: 0 },
            { value: 'Casimir', gender: 0 },
            { value: 'Félix le chat', gender: 0 },
        ],
        nomCorps: [
            {
                value: 'chatte',
                gender: 0,
            },
            {
                value: 'cul',
                gender: 1,
            },
            {
                value: 'trou',
                gender: 1,
            },
            {
                value: 'oreilles',
                gender: 2,
            },
            {
                value: 'anus',
                gender: 1,
            },
            {
                value: 'fesses',
                gender: 2,
            },
            {
                value: 'narines',
                gender: 2,
            },
            {
                value: 'vagin',
                gender: 1,
            },
        ],
        pronoms: [
            {
                value: 'je',
                withVoyelle: "j'",
                gender: 1,
            },
            {
                value: 'tu',
                withVoyelle: "t'",
                gender: 1,
            },
            {
                value: 'il',
                gender: 1,
            },
            {
                value: 'elle',
                gender: 0,
            },
            {
                value: 'on',
                gender: 2,
            },
            {
                value: 'nous',
                gender: 2,
            },
            {
                value: 'vous',
                gender: 2,
            },
            {
                value: 'ils',
                gender: 1,
            },
            {
                value: 'elles',
                gender: 0,
            },
        ],
    },
    verbes: [
        { value: 'pénètrer', degre: 1 },
        { value: 'baiser', degre: 1 },
        { value: 'défourailler', degre: 1 },
        { value: 'sucer', degre: 1 },
        { value: 'sodomiser', degre: 1 },
        { value: 'défoncer', degre: 1 },
        { value: 'enfiler', degre: 1 },
        { value: 'mouiller', degre: 1 },
        { value: 'branler', degre: 1 },
        { value: 'tromper', degre: 1 },
        { value: 'prendre', degre: 3 },
        { value: 'ramoner', degre: 1 },
        { value: 'enculer', degre: 1 },
        { value: 'galocher', degre: 1 },
        { value: 'doigter', degre: 1 },
        { value: 'niquer', degre: 1 },
        { value: 'caresser', degre: 1 },
        { value: 'biter', degre: 1 },
        { value: 'forniquer', degre: 1 },
        { value: 'casser', degre: 1 },
        { value: 'culbuter', degre: 1 },
        { value: 'labourer', degre: 1 },
        { value: 'brouter', degre: 1 },
    ],
    prepositions: {
        maniere: ['avec', 'sans', 'pour'],
        appartenance: ['de'],
        simple: ['à', 'chez', 'dans', 'entre', 'jusque', 'hors', 'par', 'vers'],
    },
    locutions: {
        adjectivales: ['comme il faut'],
        adverbiales: ['en vain'],
        conjonctives: ['pendant que', 'sans compter que'],
        interjectives: ['par exemple'],
        determinants: ['n’importe quel'],
    },
    adverbes: {
        maniere: [
            'amoureusement',
            'pépouze',
            'en tout amitié',
            'avec bienveillance',
            'goûlument',
            'salement',
            'facilement',
            'bien',
            'mieux',
            'comme',
            'exprès',
            'franco',
            'gratis',
            'incognito',
            'mal',
            'mieux',
            'plutôt',
            'presque',
            'vite',
            'volontiers',
            'admirablement',
            'bravement',
            'brutalement',
            'clairement',
            'doucement',
            'également',
            'gentiment',
            'lentement',
            'délicieusement',
        ],
        quantite: [
            'divinement',
            'drôlement',
            'encore',
            'entièrement',
            'extrêmement',
            'fort',
            'grandement',
            'guère',
            'infiniment',
        ],
        /**
         * et répitition
         */
        duree: [],
    },
    randomList: [
        'sodomie',
        'fellation',
        'baguette',
        'anal',
        'sex',
        'cohit',
        'branllette',
        'partouze',
        'orgie',
        'anus',
        'cunnilingus',
        'érotique',
        'sexe',
        'clitori',
        'con',
        'cul',
        'entre-cuisse',
        'zizi',
        'membre-virile',
        'nympho',
        'organe-génitale',
        'pénis',
        'col',
        'pubis',
        'quéquette',
        'queue',
        'sexualité',
        'vaginal',
        'verge',
        'vulve',
        'dildo',
        'encule',
        'urêtre',
        'threesome',
        'boobs',
        'chatte',
        'minou',
        'porno',
        'défoncer',
        'pénétrer',
        'masturber'
    ],
    randomListum: [
        'sodomium',
        'fellatio',
        'baguette',
        'anal',
        'sexum',
        'cohitum',
        'branlloum',
        'partouzem',
        'orgium',
        'anus',
        'cunnilingus',
        'érotisum',
        'sexus',
        'clitorisum',
        'conum',
        'cul',
        'entrecuissum',
        'membre-virilus',
        'nymphes',
        'organes-génitaum',
        'pénius',
        'coles',
        'pubisa',
        'quéquettum',
        'queuea',
        'sexualitum',
        'vagina',
        'vergem',
        'virilitum',
        'vulvus',
    ],
};
