name: Publish Documentation

on:
    push:
        # tags:
        #     - '*'
      branches:
        - master

jobs:
  publish-doc:
        runs-on: ubuntu-latest
        env:
          working-directory: packages/lorem-sexum-demo
        steps:
          - uses: actions/checkout@v1
          - uses: actions/setup-node@v1
            with:
                node-version: 12.16.3
                registry-url: https://registry.npmjs.org/
          - uses: shimataro/ssh-key-action@v2
            with:
              key: ${{ secrets.PRIVATE_SSH }}
              known_hosts: ${{ secrets.KNOWN_HOSTS }}
              name: id_rsa
          - run : npm install
          - run : npm run bootstrap
          - run : npm run build
          - run : git config --global user.email "roadfen@gmail.com"
          - run : git config --global user.name "MattMatt"
          - run : USE_SSH=true npm run publish-gh-pages
            working-directory: ${{env.working-directory}}/build